# Site settings
title: My Awesome Site
description: A brief description of my awesome site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://myusername.github.io" # the base hostname & protocol for your site

# Build settings
theme: Hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag