# Site settings
title: My Awesome Site
description: A description of my awesome site.
url: https://kvdogan.github.io
baseurl: "notes" # Leave this blank for a user page repository, or set it to the name of your project repository for a project page.

remote_theme: just-the-docs/just-the-docs

# Navigation links
# Add any links you want to appear in the navigation menu here.
# Each link should have a title and a URL.
# You can also add dropdown menus by using the "children" key.
# See the Jekyll documentation for more information.
nav_links:
  - title: Home
    url: /
  - title: Mathmatics
    url: /Mathematics
    children:
      - title: Logarithm
        url: /Mathematics/Logarithm.md
      - title: Math Definitions
        url: /Mathematics/Logarithm.md
      - title: Math Definitions
        url: /Mathematics/Math%20Definitions.md

# Social media links
# Add any social media links you want to appear in the footer here.
# Each link should have a title, a URL, and an icon.
# You can use any Font Awesome icon name for the icon.
# See the Font Awesome documentation for more information.
social_links:
  - title: GitHub
    url: https://github.com/username
    icon: fab fa-github
  - title: Twitter
    url: https://twitter.com/username
    icon: fab fa-twitter
  - title: LinkedIn
    url: https://www.linkedin.com/in/username
    icon: fab fa-linkedin