# Site settings
title: My Awesome Site
description: A description of my awesome site.
url: https://kvdogan.github.io
baseurl: "notes" # Leave this blank for a user page repository, or set it to the name of your project repository for a project page.

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


markdown_extensions:
  - attr_list
  - footnotes
  - def_list
  - tables
  - smart
  - fenced_code
  - kramdown

extra_javascripts:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML