# Site settings
title: My Awesome Site
description: A description of my awesome site.
url: https://kvdogan.github.io
baseurl: "notes" # Leave this blank for a user page repository, or set it to the name of your project repository for a project page.

remote_theme: just-the-docs/just-the-docs

# Enable MatJax math
markdown_extensions:
  - attr_list
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Social media links
# Add any social media links you want to appear in the footer here.
# Each link should have a title, a URL, and an icon.
# You can use any Font Awesome icon name for the icon.
# See the Font Awesome documentation for more information.
social_links:
  - title: GitHub
    url: https://github.com/username
    icon: fab fa-github
  - title: Twitter
    url: https://twitter.com/username
    icon: fab fa-twitter
  - title: LinkedIn
    url: https://www.linkedin.com/in/username
    icon: fab fa-linkedin