# Site settings
title: My Awesome Site
description: A description of my awesome site.
url: https://kvdogan.github.io
baseurl: "notes" # Leave this blank for a user page repository, or set it to the name of your project repository for a project page.

theme: modernist


markdown_extensions:
  - attr_list
  - footnotes
  - def_list
  - tables
  - smart
  - fenced_code
  - kramdown

extra_javascripts:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js