# Site settings
title: My Awesome Site
description: A description of my awesome site.
url: https://kvdogan.github.io
baseurl: "notes" # Leave this blank for a user page repository, or set it to the name of your project repository for a project page.

remote_theme: just-the-docs/just-the-docs

# Enable MatJax math
markdown_extensions:
  - attr_list
  - footnotes
  - def_list
  - tables
  - smart
  - fenced_code
  - mathjax:
      - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
  - kramdown:
      math_engine: mathjax
